name: Auto Commit

on:
  schedule:
   - cron: '0 4,12,15,18,19 * * *' # See https://crontab.guru/#0_4,12,15,18,19_*_*_*

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main 

    - name: Create file and commit
      run: |
        FILE="commit_number.md"
        if [ ! -f "$FILE" ]; then
          echo "Hello, my name is syahrul" > "$FILE"
          echo "commit number: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
        fi
        git config --global user.name "MuhSyahrul29"
        git config --global user.email "rulztarito29@gmail.com"
        git add "$FILE"
        git commit -m "Hello, my name is Syahrul nice to meet you"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MuhSyahrul29/mean-commit.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
